### ISSUE TITLE
Wikicommons <-> Structured data in Wikibase and support for Handle System

### ISSUE THREAD

**Issue by salgo60** [europeana/entity-api#158]
As Wikicommons now run [Wikibase](https://www.mediawiki.org/wiki/Wikibase) we also get structured data for pictures see example [M70051666 JSON](https://commons.wikimedia.org/wiki/Special:EntityData/M70051666.json?action=purge) [link](https://phabricator.wikimedia.org/T243907#5914827)...

==> that one picture object in Europeana can be same as a picture object in Wikicommons and same as a picture object in a local museum --> that we can start enrich each others pictures with the metadata used on all platforms....

To support data round tripping we need to have **a relation** between  an Europeana picture and a Wikicommon object see example  [M70051666 JSON](https://commons.wikimedia.org/wiki/Special:EntityData/M70051666.json?action=purge)

If you check the example [Welsh Portrait Collection](https://phabricator.wikimedia.org/T243907#5914827) they support the [Handle System](https://en.wikipedia.org/wiki/Handle_System) e.g 10107/4671365 ==> https://hdl.handle.net/10107/4671365

**Question Europeana project**: To get better integration between pictures on Wikicommons and Europeana it would be nice if Europeana also supported the [Handle System](https://en.wikipedia.org/wiki/Handle_System) and that this identifier is stable and persistent

Example test see [T243907#5906655](https://phabricator.wikimedia.org/T243907#5906655 ) 
* Europeana using ID  [2022608/OMU_OB_FS0892](http://data.europeana.eu/item/2022608/OMU_OB_FS0892) (**Question**: is this ID stable?)
* Wikicommons  [commons:File:Eivind_Groven_og_Albert_Schweitzer_OB.FS0892.jpg](https://commons.wikimedia.org/wiki/File:Eivind_Groven_og_Albert_Schweitzer_OB.FS0892.jpg) same as [Special:EntityData/M63516379](https://commons.wikimedia.org/wiki/Special:EntityData/M63516379.json)
  * [version history](https://commons.wikimedia.org/w/index.php?title=File:Eivind_Groven_og_Albert_Schweitzer_OB.FS0892.jpg&action=history) File:Eivind_Groven_og_Albert_Schweitzer_OB.FS0892.jpg
* Digitalmuseum [011014651264](https://digitaltmuseum.org/011014651264/) = [json](https://api.dimu.org/artifact/uuid/095722B0-666C-40EA-80EA-2E899E708BBB)

**Comment by hugomanguinhas** [comment]
Dear user,

We have defined URIs for our items under the data.europeana.eu domain which we are committed to remain resolvable for as long as Europeana exists. The possible issues with the identifiers have been explained in several forums and we actively put an effort on making sure that they are kept resolvable. With regards to the Entities, there are no issues that we are aware of when it comes to Entity URIs not being resolvable. 

About the Handle System, we dont see it as offering any kind of solution to this... and we prefer to keep maintaining and promoting the use of Europeana URIs whenever an item from Europeana is referenced. 

Sincerely,
The Europeana API team

**Comment by salgo60** [comment]
Thanks the benefit I see is if we like DOI ORCID get **one** standard way that will make it easy and faster.... and in Wikidata/Wikicomons we dont have ti create new properties for all new systems... 

**Off Topic:** all 160 000 Wikidata URLS stopped working today see https://europeana.atlassian.net/browse/PRO-60?atlOrigin=eyJpIjoiM2ExYjE5ODk3ZDFlNDUxM2I5ZWIxZWE1MWMyMzUxMzciLCJwIjoiaiJ9

or  my task https://phabricator.wikimedia.org/T247719#5983258
