### ISSUE TITLE
Update import scripts to use Wikidata pagerank index

### ISSUE THREAD

**Issue by rgraf** [europeana/entity-api#180]
The import scripts for Entities should use the Wikidata pagerank index

**Comment by salgo60** [comment]
?!?!? please explain. I think Europeana should use what is in local language versions of Wikidata for artists and try to add artist that are missing....  you have a great tool in Categories.....

The advantage of Europeana is if we can gather all of Europes artists and also small local ones... the most ranked is a rather bad measure

- Example
  * Wikidata [Q9817368](https://www.wikidata.org/wiki/Q9817368#sitelinks-wikipedia)  is the category for sami artists
    * on [en:Wikipedia we have 15](https://en.wikipedia.org/wiki/Category:Sami_artists)
    * on [sv:Wikipedia we have 41](https://sv.wikipedia.org/wiki/Kategori:Samiska_konstn%C3%A4rer)
    * on [se:Wikipedia we have 60](https://se.wikipedia.org/wiki/Kategoriija:S%C3%A1mi_d%C3%A1idd%C3%A1rat)
    * ....

**Comment by gsergiu** [comment]
Hi Salgo, 

The wikidata page rank is computed over all versions. But this ticket was placed to the wrong repository, tehrefore I close it

**Comment by gsergiu** [comment]
entity import is part of other repository

**Comment by salgo60** [comment]
@gsergiu I matched [160 000 Europeana agents in 2020-jan](https://phabricator.wikimedia.org/T240290) --> then you can now use a tool Petscan to find good candidates for imports in Europeana let me know if you need more info

* Example 
  * en:Wikipedia [Category:Romanian_artists](https://en.wikipedia.org/wiki/Category:Romanian_artists) has Wikidata [Q8680284](https://www.wikidata.org/wiki/Q8680284) --> we can see that the Romanian WIkipedia rowiki has [Categorie:Artiști români](https://ro.wikipedia.org/wiki/Categorie:Arti%C8%99ti_rom%C3%A2ni)

as the Europeana agent import added agents in Wikidata Property [Property:P7704](https://www.wikidata.org/wiki/Property:P7704) the SPARQL is https://w.wiki/Qbx -> we get > 160000 items

Using the Tool Petscan we can ask find all articles in a category and its subcategories that is not in Europeana ->

1. Ask Petscan for all [members in the en:WIkipedia category and 4 level down](http://petscan.wmflabs.org/?psid=16227784) --> **447 articles**

   1. ask for all members in this category but not in Europeana using the above SPARQL and Petscan "categories NOT sparql" --> **very slow query** but we get 282 artists missing in Europeana http://petscan.wmflabs.org/?psid=16227795

1. same for rowiki that is a local wiki and normally has more artists http://petscan.wmflabs.org/?psid=16227799 --> **6965 articles**

   1. ask for all members in this category but not in Europeana  --> **very slow query**  http://petscan.wmflabs.org/?psid=16227802 --> **6500 artists/articles** missing un Europeana as agents

[video](https://youtu.be/qokPJx40Ke8)
